### ISSUE TITLE
What is iVindie ?

### ISSUE THREAD

**Issue by locness3** [iVindie/client#1]
@BloxyGithub I would like to know what is iVindie. I would like to know what I am contributing to.

**Comment by BloxyGithub** [comment]
iVindie is a bit like itch.io

**Comment by locness3** [comment]
Oh

**Comment by locness3** [comment]
Will you use Firebase ? (or other JS databases) If you don't, you will need to host somewhere else.

**Comment by BloxyGithub** [comment]
I will use firebase

**Comment by locness3** [comment]
Or you could use jsonstore.io. In the two cases, try to find a way to hide your database key.

**Comment by BloxyGithub** [comment]
Whats that?

**Comment by locness3** [comment]
The database key is a kind of password/token, that firebase (indirectly) or jsonstore.io gives you. If someone has access to it, he can do anything with your database.

**Comment by BloxyGithub** [comment]
o gawd, k ill do that

**Comment by locness3** [comment]
How ?

**Comment by AyzansAlt** [comment]
.env files
